apiVersion: v1
kind: Service
metadata:
  labels:
    app: vgsales-weblogs
  name: vgsales-weblogs
spec:
  selector:
    app: vgsales-weblogs
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30000
    protocol: TCP
